export const movies = [
  {
    id: 1,
    jenis: "Movie",
    img: "../images/p-1.jpg",
    url: "../page/movie-page-paranormal.html",
    summary:
      "Jesse yang berusia tujuh belas tahun telah mendengar suara-suara mengerikan yang berasal dari apartemen tetangganya, tetapi ketika ia menyalakan kameranya dan berusaha untuk mengungkap sumber suara-suara itu, ia menemukan kejahatan kuno yang tidak akan berhenti sampai merenggut jiwanya.",
    title: "Paranormal Activity: The Marked Ones",
    rating: "5.4",
    year: "2014",
    durasi: "",
    language: "English",
    Genre: ["Horror", "Mistery", "Thriller"],
    screenshot: [
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-1.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-2.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-3.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-4.jpg",
    ],
    trailer: "https://youtu.be/ccE9LeAbPU4?si=2clL7gWdrLXW4KlS",
    link480p: "https://sfl.gl/Paranormal14480p",
    link720p: "https://sfl.gl/Paranormal14720p",
    link1080p: "https://sfl.gl/Paranormal141080p",
  },
  {
    id: 2,
    jenis: "Movie",
    img: "../images/p-2.jpg",
    url: "../page/movie-page-pirates.html",
    summary:
      "Untuk mematahkan kutukan Flying Dutchman, Jack Sparrow dan Henry Turner mulai mencari tombak Trident of Poseidon. Keduanya juga berusaha menghentikan Kapten Salazar yang ingin untuk menguasai lautan.",
    title: "Pirates of the Caribbean Salazars Revenge",
    rating: "6.5",
    year: "2017",
    durasi: "",
    language: "English",
    Genre: ["Action", "Adventure", "Fantasy"],
    screenshot: [
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-1.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-2.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-3.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-4.jpg",
    ],
    trailer: "https://youtu.be/BrX5op6_9uw?si=8NCmUxYi4zqifUyS",
    link480p: "#",
    link720p: "#",
    link1080p: "https://sfl.gl/Salazars",
  },
  {
    id: 3,
    jenis: "Movie",
    img: "../images/p-3.jpg",
    url: "../page/movie-page-bloodshot.html",
    summary:
      "Ray Garrison, seorang prajurit elit yang tewas dalam pertempuran, dihidupkan kembali oleh teknologi canggih yang memberinya kemampuan kekuatan manusia super dan penyembuhan cepat. Dengan kemampuan barunya, ia mengejar pria yang membunuh istrinya, atau setidaknya, yang ia yakini telah membunuh istrinya. Ia segera mengetahui bahwa tidak semua yang ia pelajari dapat dipercaya. Pertanyaan sebenarnya adalah: Bisakah ia mempercayai dirinya sendiri?",
    title: "BloodShot",
    rating: "5.7",
    year: "2020",
    durasi: "",
    language: "English",
    Genre: ["Action", "Sci-Fi", "Thriller"],
    screenshot: [
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-1.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-2.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-3.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-4.jpg",
    ],
    trailer: "https://youtu.be/vOUVVDWdXbo",
    link480p: "https://sfl.gl/BloodShot22480p",
    link720p: "https://sfl.gl/BloodShot22720p",
    link1080p: "https://sfl.gl/BloodShot221080p",
  },
  {
    id: 4,
    jenis: "Movie",
    img: "../images/p-4.jpg",
    url: "../page/movie-page-venom.html",
    summary:
      "Eddie Brock berjuang untuk menyesuaikan diri dengan kehidupan barunya sebagai inang dari simbiot alien Venom, yang memberinya kemampuan super untuk menjadi seorang vigilante yang mematikan. Brock mencoba menghidupkan kembali kariernya dengan mewawancarai pembunuh berantai Cletus Kasady, yang menjadi inang dari simbiot Carnage dan melarikan diri dari penjara setelah eksekusi yang gagal.",
    title: "Venom: Let There Be Carnage",
    rating: "5.9",
    year: "2021",
    durasi: "1 j 37 m",
    language: "English",
    Genre: ["Action", "Adventure", "Fantasy"],
    screenshot: [
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-1.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-2.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-3.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-4.jpg",
    ],
    trailer: "https://youtu.be/-FmWuCgJmxo?si=XpBtIPVYHwy1JlEh",
    link480p: "https://sfl.gl/Venom21480p",
    link720p: "https://sfl.gl/Venom21720p",
    link1080p: "https://sfl.gl/Venom21180p",
  },
  {
    id: 5,
    jenis: "Movie",
    img: "../images/p-5.jpg",
    url: "../page/movie-page-deadpool2.html",
    summary:
      "Setelah kehilangan Vanessa (Morena Baccarin), cinta dalam hidupnya, tentara bayaran pendobrak dinding keempat Wade Wilson, alias Deadpool (Ryan Reynolds), harus mengumpulkan tim dan melindungi mutan muda Russell Collins, alias Firefist (Julian Dennison), dari Cable (Josh Brolin), seorang cyborg berbahaya dan tak kenal basa-basi dari masa depan, dan juga harus mempelajari pelajaran yang paling penting dari semuanya: menjadi bagian dari sebuah keluarga lagi.",
    title: "Deadpool 2",
    rating: "7.6",
    year: "2018",
    durasi: "",
    language: "English",
    Genre: ["Action", "Sci-Fi", "Thriller"],
    screenshot: [
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-1.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-2.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-3.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-4.jpg",
    ],
    trailer: "https://youtu.be/D86RtevtfrA?si=8iF6csSQcHOOI8Cs",
    link480p: "https://sfl.gl/DeadPool218480p",
    link720p: "https://sfl.gl/DeadPool218720p",
    link1080p: "https://sfl.gl/DeadPool2181080p",
  },
  {
    id: 6,
    jenis: "Movie",
    img: "../images/p-6.jpg",
    url: "../page/movie-page-blackwidow.html",
    summary:
      "Dalam film penuh aksi Marvel Studios’ “Black Widow”, Natasha Romanoff alias Black Widow harus menghadapi sisi gelap hidupnya saat sebuah konspirasi berbahaya dikaitkan dengan masa lalunya. Dikejar oleh sesuatu yang tidak akan berhenti sampai berhasil menghancurkan hidupnya, Natasha harus kembali pada kenyataan bahwa ia adalah seorang mata-mata dan hubungan keluarganya yang hancur sebelum ia bergabung bersama Avengers.",
    title: "Black Widow",
    rating: "6.6",
    year: "2021",
    durasi: "",
    language: "English",
    Genre: ["Adventure", "Drama", "Sci-Fi"],
    screenshot: [
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-1.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-2.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-3.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-4.jpg",
    ],
    trailer: "https://youtu.be/RxAtuMu_ph4?si=vipwmUmh-oRp1q9r",
    link480p: "https://sfl.gl/BlackWidow480p",
    link720p: "https://sfl.gl/BlackWidow720p",
    link1080p: "https://sfl.gl/BlackWidow1080p",
  },
  {
    id: 7,
    jenis: "Anime, Movie",
    img: "../images/Your_Name_poster.jpg",
    url: "../page/movie-page-yourname.html",
    summary:
      "Mitsuha dan Taki siswa sekolah menengah adalah orang asing yang menjalani kehidupan terpisah. Tapi suatu malam, mereka tiba-tiba bertukar tempat. Mitsuha bangun di tubuh Taki, dan dia di dalam tubuh Taki. Kejadian aneh ini terus terjadi secara acak, dan keduanya harus menyesuaikan kehidupan mereka satu sama lain.",
    title: "Your Name.",
    rating: "8.4",
    year: "2016",
    durasi: "",
    language: "Japanese",
    Genre: ["Drama", "Fantasy", "Romance"],
    screenshot: [
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-1.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-2.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-3.jpg",
      "../Movie-Data/Pirates-of-the-Caribbean-Salazar's-Revenge/screenshot-4.jpg",
    ],
    trailer: "https://youtu.be/xU47nhruN-Q",
    link480p: "https://sfl.gl/YourName16480p",
    link720p: "https://sfl.gl/YourName16720p",
    link1080p: "https://sfl.gl/YourName161080p",
  },
];
